apiVersion: apps/v1
kind: Deployment
metadata:
  name: timelogger
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timelogger
  template:
    metadata:
      labels:
        app: timelogger
    spec:
      containers:
      - name: timelogger
        image: ghcr.io/dalewyz/jx-deploy-test-1221:${VERSION}
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m" 
      imagePullSecrets:
      - name: tekton-container-registry-auth
