# Tekton PipelineRun 资源定义
# 用于处理 Pull Request 的流水线配置
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest  # 流水线运行的名称
spec:
  params:
    - name: REPO_URL
      value: "https://github.com/DaleWYZ/jx-deploy-test-1221.git"
    - name: revision
      value: $(params.pull_base_ref)
    - name: pull_base_ref
      value: main
  workspaces:
    - name: shared-data
      emptyDir: {}
  pipelineSpec:
    params:
      - name: repo_url
        type: string
        description: "代码仓库的 URL"
      - name: revision
        type: string
        description: "要检出的分支或提交"
      - name: pull_base_ref
        type: string
        description: "PR 的基础分支"
    workspaces:
      - name: shared-data
    tasks:
    - name: from-build-pack
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: shared-data
          # workspace表示任务使用的工作空间名称
          # 工作空间名称可以随便起，但需要与上面定义的名称一致
          workspace: shared-data
      taskSpec:
        params:
          - name: repo_url
            type: string
          - name: revision
            type: string
        workspaces:
          - name: shared-data
            description: "用于在步骤之间共享数据的工作空间"
        stepTemplate:
          image: golang:1.21
          workingDir: $(workspaces.shared-data.path)
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
            limits:
              cpu: "1"
              memory: "2Gi"
          env:
            - name: DOCKER_REGISTRY
              value: harbor.corp.angoo.io
            - name: APP_NAME
              value: timelogger
        steps:
        - image: alpine/git:v2.30.2
          name: git-clone
          script: |
            git clone $(params.repo_url) .
            git checkout $(params.revision)
        
        - name: build-make-linux
          command:
            - make
            - build
        
        - name: build-container-build
          command:
            - skaffold
            - build
        
        - name: promote-jx-preview
          command:
            - jx
            - preview
            - --app timelogger
            - --dir ../..
  
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
