# Tekton PipelineRun 资源定义
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        taskSpec:
          steps:
            - name: git-clone
              image: alpine/git:v2.30.2
              script: |
                git clone $(params.REPO_URL) .
                git checkout $(params.revision)

            - name: build
              image: golang:1.21
              script: |
                make build

            - name: container-build
              image: gcr.io/kaniko-project/executor:latest
              env:
                - name: DOCKER_REGISTRY
                  value: harbor.corp.angoo.io
                - name: APP_NAME
                  value: timelogger
              script: |
                /kaniko/executor \
                  --context=. \
                  --dockerfile=Dockerfile \
                  --destination=${DOCKER_REGISTRY}/${APP_NAME}:pr-${PULL_NUMBER}

            - name: preview
              image: gcr.io/jenkinsxio/jx:latest
              env:
                - name: APP_NAME
                  value: timelogger
              script: |
                jx preview create \
                  --app ${APP_NAME} \
                  --app-version pr-${PULL_NUMBER}

  serviceAccountName: tekton-bot
  timeout: 1h0m0s
