apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependSteps: "true"
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        taskSpec:
          metadata:
            labels:
              app.kubernetes.io/name: 'timelogger'
          stepTemplate:
            image: golang:1.21
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: "1"
                memory: 2Gi
          steps:
            - name: test
              command:
                - make
                - test
                
            - name: build
              command:
                - make
                - build 