apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: golang:1.21
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
            limits:
              cpu: "1"
              memory: "2Gi"
          workingDir: /workspace/source
          env:
            - name: DOCKER_REGISTRY
              value: harbor.corp.angoo.io
            - name: APP_NAME
              value: timelogger
        steps:
        - image: alpine/git:v2.30.2
          name: git-clone
          script: |
            git clone $(params.repo_url) .
            git checkout $(params.revision)
        - name: build-make-linux
          command:
            - make
            - build
        - name: build-container-build
          command:
            - skaffold
            - build
        - name: promote-jx-preview
          command:
            - jx
            - preview
            - --app timelogger
            - --dir ../..
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
