apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependSteps: "true"
  name: pullrequest
spec:
  workspaces:
    - name: source
      emptyDir: {}
  pipelineSpec:
    workspaces:
      - name: source
    tasks:
      - name: from-build-pack
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          metadata:
            labels:
              app.kubernetes.io/name: 'timelogger'
          stepTemplate:
            image: golang:1.21
            workingDir: $(workspaces.source.path)
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: "1"
                memory: 2Gi
          steps:
            - name: git-clone
              image: alpine/git:v2.30.2
              script: |
                git clone $(params.repo_url) .
                git checkout $(params.revision)
                
            - name: test
              command:
                - make
                - test
                
            - name: build
              command:
                - make
                - build