apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: golang:1.21
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
            limits:
              cpu: "1"
              memory: "2Gi"
          workingDir: /workspace/source
          env:
            - name: DOCKER_REGISTRY
              value: harbor.corp.angoo.io
            - name: APP_NAME
              value: timelogger
        steps:
        - image: alpine/git:v2.30.2
          name: git-clone
          script: |
            git clone $(params.repo_url) .
            git checkout $(params.revision)
        - name: next-version
          image: gcr.io/jenkinsxio/jx-release-version:2.2.3
          command:
            - jx-release-version
        - name: build-make-build
          command:
            - make
            - build
        - name: build-container-build
          command:
            - skaffold
            - build
            - -p
            - release
        - name: promote-changelog
          command:
            - jx
            - changelog
            - create
            - --verbose
            - --header-file=hack/changelog-header.md
            - --version=$(VERSION)
            - --rev=$(PULL_BASE_SHA)
            - --output-markdown=changelog.md
            - --update-release=false
        - name: promote-helm-release
          command:
            - jx
            - promote
            - --app timelogger
            - --version $(VERSION)
            - --env production
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
