apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/release.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 600Mi
        - name: build-make-build
          resources: {}
        - name: check-registry
          resources: {}
        - name: build-container-build
          resources: {}
        - name: promote-changelog
          resources: {}
            #- name: promote-helm-release
            # resources: {}
        - name: promote-jx-promote
          script: |
            #!/bin/sh
            # 加载变量
            jx gitops variables

            # 替换部署文件中的变量
            VERSION=$(cat VERSION)
            DOCKER_REGISTRY=$(cat DOCKER_REGISTRY)
            APP_NAME=$(cat APP_NAME)
            sed -i "s/\${VERSION}/$VERSION/g" deploy/k8s/deployment.yaml
            sed -i "s/\${DOCKER_REGISTRY}/$DOCKER_REGISTRY/g" deploy/k8s/deployment.yaml
            sed -i "s/\${APP_NAME}/$APP_NAME/g" deploy/k8s/deployment.yaml
            # 应用部署
            kubectl apply -f deploy/k8s/deployment.yaml
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
